// src/utils/exportProject.js
import JSZip from "jszip";
import { saveAs } from "file-saver";

export async function exportProject(projectName, codeString) {


  const name = typeof projectName === "string" ? projectName : "Untitled_Project";
  const zip = new JSZip();

  // ✅ Basic React project structure
  const pkg = {
    name: name.toLowerCase().replace(/\s+/g, "-"),
    version: "1.0.0",
    private: true,
    dependencies: {
      react: "^18.2.0",
      "react-dom": "^18.2.0",
      "react-scripts": "5.0.1"
    },
    scripts: {
      start: "react-scripts start",
      build: "react-scripts build",
      test: "react-scripts test",
      eject: "react-scripts eject"
    }
  };

  // Folder structure
  const src = zip.folder("src");
  src.file("App.js", codeString);
  src.file(
    "index.js",
    `
import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";

const root = ReactDOM.createRoot(document.getElementById("root"));
root.render(<App />);
`
  );

  // Public folder
  const publicFolder = zip.folder("public");
  publicFolder.file(
    "index.html",
    `
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${name}</title>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`
  );

  // Root files
  zip.file("package.json", JSON.stringify(pkg, null, 2));
  zip.file(
    "README.md",
    `# ${name}

This project was generated by **Video Sandbox AI**.

## 🚀 Getting Started

1. Unzip the folder
2. Run:
   \`\`\`bash
   npm install
   npm start
   \`\`\`
`
  );

  // ✅ Generate zip and trigger download
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${name.replace(/\s+/g, "_")}.zip`);
}
